services:
    predict:
        container_name: ocr2pdf
        build: ./src
        command: bash predict.sh pdf -l eng+fra
        volumes:
            - ./src:/ocr2pdf
            - ./pdf:/ocr2pdf/pdf
