name: predict

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    # GitHub Actions run without a TTY device. This is a workaround to get one,
    # based on https://github.com/actions/runner/issues/241#issuecomment-2019042651
    shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"'

jobs:
  inference:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run inference
        run: |
          docker run \
            -v ./src:/app \
            -v ./pdf:/app/pdf \
            ghcr.io/ipitio/ocr-pdf \
            bash predict.sh pdf

      - name: Save predictions
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "**/*.pdf"
          message: "processed files"
