name: scan

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dry run
        id: scan
        run: bash main.sh ; echo "scanned=$?" >> "$GITHUB_OUTPUT"

      - name: Merge changes
        id: commit
        if: ${{ steps.scan.outputs.scanned == '0' }}
        uses: EndBug/add-and-commit@v9
        with:
          add: "*.pdf"
          message: "scanned pdfs"
          pull: "--autostash -s ours"
